BReports/Models/DBModels/Sale.cs
using System;

namespace BReports.Models.DBModels
{
    public class Sale
    {
        public int Id { get; set; }
        public Product Product { get; set; }
        public ApplicationUser SoldBy { get; set; }
        public double Amount { get; set; }
        public string Description { get; set; } 
        public string CustomerId { get; set; } 
        public DateTime SaleDate { get; set; }
        public bool IsDeleted { get; set; }
    }
}

BReports/Models/ViewModels/SaleViewModel.cs
using BReports.Models.DBModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;

namespace BReports.Models.ViewModels
{
    public class SaleViewModel
    {
        public int Id { get; set; }
        public Category Category { get; set; }
        public Product Product { get; set; }
        public ApplicationUser User { get; set; }
        public double Amount { get; set; }
        public string Description { get; set; }
        public string CustomerId { get; set; }
        public DateTime SaleDate { get; set; }
        public bool IsDeleted { get; set; }
        public List<SelectListItem> ProductsList {get; set;}
        public List<SelectListItem> CategoriesList { get; set;}
    }
}

BReports/Controllers/SalesController.cs
using BReports.Models.DBModels;
using BReports.Models.ViewModels;
using BReports.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;

namespace BReports.Controllers
{
    public class SalesController : Controller
    {
        private readonly ISaleRepository saleService;
        private readonly IProductRepository productService;
        private readonly ICategoryRepository categoryService;
        public SalesController(ISaleRepository saleService, IProductRepository productService, ICategoryRepository categoryService)
        {
            this.saleService = saleService;
            this.productService = productService;
            this.categoryService = categoryService;
        }

        public IActionResult Index()
        {
            var sales = this.saleService.GetAll();
            var model = new SaleViewModelList
            {
                List = GetSaleViewModel(sales)

            };
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new SaleViewModel();
            var categoriesData = categoryService.GetAll();
            var productsData = productService.GetAll();

            model.ProductsList = new List<SelectListItem>();
            model.CategoriesList = new List<SelectListItem>();

            foreach (var category in categoriesData)
            {
                model.CategoriesList.Add(new SelectListItem { Text = category.Name, Value = category.Id.ToString() });
            }
            foreach (var product in productsData)
            {
                model.ProductsList.Add(new SelectListItem { Text = product.Name, Value = product.Id.ToString() });
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(SaleViewModel sale)
        {
            this.saleService.Create(GetSaleDataModel(sale));
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int saleId)
        {
            var sale = this.saleService.GetById(saleId);
            var model = GetSaleViewModel(sale);
            if (sale == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(SaleViewModel sale)
        {
            this.saleService.Update(GetSaleDataModel(sale));
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            this.saleService.Delete(id);
            return RedirectToAction("Index");
        }
        private Sale GetSaleDataModel(SaleViewModel sale)
        {
            return new Sale
            {
                Id = sale.Id,
                Product = sale.Product,
                SoldBy = sale.User,
                CustomerId = sale.CustomerId,
                Description = sale.Description,
                Amount = sale.Amount,
                SaleDate = DateTime.Now
            };
        }

        private SaleViewModel GetSaleViewModel(Sale sale)
        {

            return new SaleViewModel
            {
                Id = sale.Id,
                Product = sale.Product,
                User = sale.SoldBy,
                CustomerId = sale.CustomerId,
                Description = sale.Description,
                Amount = sale.Amount,
                SaleDate = sale.SaleDate
            };
        }
        private List<SaleViewModel> GetSaleViewModel(List<Sale> source)
        {
            var sales = new List<SaleViewModel>();

            foreach (var element in source)
            {
                sales.Add(GetSaleViewModel(element));
            }
            return sales;
        }
    }
}

BReports/Views/Sales/Create.cshtml
@model SaleViewModel

<h3 class="my-4">Добави продажба</h3>
<form method="post" asp-controller="Sales" asp-action="Create">
      <div class="mb-3">
        <label class="form-label">Категория</label>
        <select class="form-control" asp-items="Model.CategoriesList" asp-for="Category"></select>
    </div>
    <div class="mb-3">
        <label class="form-label">Продукт</label>
        <select class="form-control" asp-items="Model.ProductsList" asp-for="Product"></select>
    </div>
    <div class="mb-3">
        <label class="col-form-label" asp-for="Amount">Сума</label>
        <input class="form-control" asp-for="Amount" />
    </div>
    <div class="mb-3">
        <label class="col-form-label" asp-for="Description">Описание</label>
        <input class="form-control" asp-for="Description" />
    </div>
    <div class="mb-3">
        <label class="col-form-label" asp-for="CustomerId">Клиентски номер</label>
        <input class="form-control" asp-for="CustomerId" />
    </div>
    <div class="mb-3">
        <label class="col-form-label" asp-for="SaleDate">Дата</label>
        <input type="date" class="form-control" asp-for="SaleDate" asp-format="{0:yyyy-MM-ddTHH:mm}" value="@DateTime.Now" />
    </div>
    <button class="btn btn-info mt-3">Запази</button>
</form>

BReports/Views/Sales/Edit.cshtml
@model SaleViewModel


<h3 class="mb-2">Редактиране на продажба</h3>

<form method="post">
    <div class="form-group">
        <label asp-for="Category" class="form-label"></label>
        <input asp-for="Category" class="form-control" placeholder="@Model?.Category" />
        <span asp-validation-for="Category" class="text-danger"></span>
    </div>
      <div class="form-group">
        <label asp-for="Product" class="form-label"></label>
        <input asp-for="Product" class="form-control" placeholder="@Model?.Product" />
        <span asp-validation-for="Product" class="text-danger"></span>
    </div>
      <div class="form-group">
        <label asp-for="Description" class="form-label"></label>
        <input asp-for="Description" class="form-control" placeholder="@Model?.Description" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Amount" class="form-label"></label>
        <input asp-for="Amount" class="form-control" placeholder="@Model?.Amount" />
        <span asp-validation-for="Amount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-dark">Запази </button>
        <a asp-action="Index" class="btn btn-primary">Cancel</a>
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>
</form>

BReports/Views/Sales/Index.cshtml
@model SaleViewModelList


<h1>Продажби</h1>
<a class="btn btn-outline-info my-2" href="/Sales/Create">Добави продажба</a>

@if (Model == null)
{
    <h3>Няма налични продажби</h3>

}
else
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Category</th>
                <th scope="col">Product</th>
                <th scope="col">Sold by</th>
                <th scope="col">Customer Id</th>
                <th scope="col">Description</th>
                <th scope="col">Amount</th>
                <th scope="col">Date of sale</th>
                <th scope="col">Actions</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var sale in Model.List)
            {
                <tr>
                    <th> @sale.Category</th>
                    <th> @sale.Product</th>
                    <th> @User.Identity.Name</th>
                    <th> @sale.CustomerId</th>
                    <th> @sale.Description</th>
                    <th> @sale.Amount</th>
                    <th> @sale.SaleDate</th>
                    <th>
                        <a class="btn btn-info" asp-action="Edit" asp-controller="Sales" asp-route-id="@sale.Id">Редактирай</a>
                        <button class="btn btn-danger" data-toggle="modal" data-target="#deleteSale">
                            Изтрий
                        </button>
                    </th>
                </tr>
                <div class="modal fade" id="deleteSale" tabindex="-1" role="dialog" aria-labelledby="Sale" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="Sale">Изтрий продажба</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Сигурни ли сте, че желаете да изтриете продажбата?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Откажи</button>
                                <form asp-action="Delete" asp-route-id="@sale.Id" method="post">
                                    <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Sales" asp-route-id="@sale.Id">Изтрий</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </tbody>
    </table>
}