BReports/Models/DBModels/Location.cs
namespace BReports.Models.DBModels
{
    public class Location
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Region { get; set; }
        public bool IsDeleted { get; set; }
    }
}

BReports/Models/ViewModels/LocationViewModel.cs
namespace BReports.Models.ViewModels
{
    public class LocationViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Region { get; set; }
        public bool IsDeleted { get; set; }
    }
}

BReports/Controllers/LocationsController.cs
using BReports.Models.DBModels;
using BReports.Models.ViewModels;
using BReports.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace BReports.Controllers
{
    public class LocationsController : Controller
    {
        private readonly ILocationRepository locationService;

        public LocationsController(ILocationRepository locationService)
        {
            this.locationService = locationService;
        }

        public IActionResult Index()
        {
            var locations = this.locationService.GetAll();
            return View(GetLocationViewModel(locations));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Location location)
        {
            this.locationService.Create(location);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            var location = this.locationService.GetById(id);
            var model = GetLocationViewModel(location);
            if (location == null)
            {
                return NotFound();
            }
            return View(model);
        }
        [HttpPost]
        public IActionResult Edit(LocationViewModel location)
        {
            this.locationService.Update(GetLocationDataModel(location));
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            this.locationService.Delete(id);
            return RedirectToAction("Index");
        }

        private Location GetLocationDataModel(LocationViewModel location)
        {
            return new Location
            {
                Id = location.Id,
                Name = location.Name,
                Region = location.Region
            };
        }

        private LocationViewModel GetLocationViewModel(Location location)
        {
            return new LocationViewModel
            {
                Id = location.Id,
                Name = location.Name,
                Region = location.Region
            };
        }
        private List<LocationViewModel> GetLocationViewModel(List<Location> source)
        {
            var locations = new List<LocationViewModel>();

            foreach (var loc in source)
            {
                locations.Add(GetLocationViewModel(loc));
            }
            return locations;
        }
    }
}

BReports/Views/Locations/Create.cshtml
@model LocationViewModel

<button onclick="history.back()" class="btn btn-outline-info my-3">Назад</button>
<h3>Добави офис</h3>

<form asp-controller="Locations" asp-action="Create">
    <label class="col-form-label" asp-for="Name">Офис</label>
    <input class="form-control" asp-for="Name"/>
    <label class="col-form-label" asp-for="Region">Регион</label>
    <input class="form-control" asp-for="Region" />
    <button class="btn btn-info mt-3">Запази</button>
</form>

BReports/Views/Locations/Edit.cshtml
@model LocationViewModel

<button onclick="history.back()" class="btn btn-outline-info my-3">Назад</button>
<h3>Редактирай офис</h3>

<form asp-controller="Locations" asp-action="Edit">
    <label class="col-form-label" asp-for="Name"></label>
    <input class="form-control" asp-for="Name" placeholder="@Model?.Name"/>
    <label class="col-form-label" asp-for="Region"></label>
    <input class="form-control" asp-for="Region" placeholder="@Model?.Region" />
    <button class="btn btn-info mt-3">Запази</button>
</form>

BReports/Views/Locations/Index.cshtml
@model List<LocationViewModel>

<h2>Офиси</h2>
<a class="btn btn-info my-3" href="/Locations/Create">Добави офис</a>
@if (Model == null)
{
    <h3>Няма налични офиси</h3>
}
else
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Office</th>
                <th scope="col">Region</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var location in Model)
            {

                <tr>
                    <th> @location.Name</th>
                    <th> @location.Region</th>
                    <th>
                        <a class="btn btn-info" asp-action="Edit" asp-controller="Locations" asp-route-id="@location.Id">Редактирай</a>
                        <button class="btn btn-danger" data-toggle="modal" data-target="#deleteLocation">
                            Изтрий
                        </button>
                    </th>
                </tr>
                <div class="modal fade" id="deleteLocation" tabindex="-1" role="dialog" aria-labelledby="Location" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="User">Изтрий офис</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Сигурни ли сте, че желаете да изтриете офиса?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Откажи</button>
                                <form asp-action="Delete" asp-route-id="@location.Id" method="post">
                                    <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Locations" asp-route-id="@location.Id">Изтрий</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </tbody>
    </table>
}